---
# Lambda School Data Science - Intro to Python  
---
# Assignment 04 - Intro to `numpy`
---



##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_assign4"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!

---


## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [133]:
# Import numpy and assign it the standard alias
import numpy as np

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [134]:
# Generate your random numbers
myarray = np.random.randint(0,100, size = (5,3))
print (myarray)
print (myarray.shape)

np.random.seed(42)


[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]]
(5, 3)


### 1.3 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [135]:
# 1. Return the first row:
myarray[0]

array([51, 92, 14])

In [136]:
# 2. Return the last column
myarray[:,2]

array([14, 20, 74, 99, 21])

In [137]:
# 3. Return the third column values from the 4th and 5th rows
myarray[3:,2]



array([99, 21])

In [138]:
# 4. Multiply every value in the array by 2
myarray*2


array([[102, 184,  28],
       [142, 120,  40],
       [164, 172, 148],
       [148, 174, 198],
       [ 46,   4,  42]])

In [139]:
# 5. Divide every value by 3
myarray/3



array([[17.        , 30.66666667,  4.66666667],
       [23.66666667, 20.        ,  6.66666667],
       [27.33333333, 28.66666667, 24.66666667],
       [24.66666667, 29.        , 33.        ],
       [ 7.66666667,  0.66666667,  7.        ]])

In [140]:
# 6. Increase the values in the first row by 12
myarray[0,:]+12



array([ 63, 104,  26])

In [141]:
# 7. Calculate the mean of the first column
mean = np.mean(myarray[:,0])
print (mean)

60.2


In [142]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array

# flatten and sort (axis=None does the flattening)
sortedArray = np.sort(myarray, axis = None)
print (sortedArray)
# remove two smallest values
new_sortedArray = sortedArray[2:]
print (new_sortedArray)
print (a)

# calculate the median


median = np.median(new_sortedArray)
print (median)


[ 2 14 20 21 23 51 60 71 74 74 82 86 87 92 99]
[20 21 23 51 60 71 74 74 82 86 87 92 99]
1
74.0


In [143]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
new_array = myarray
# print (new_array)
print (new_array[:3,:])
sd = np.std(new_array[:3,:])
print (sd)

[[51 92 14]
 [71 60 20]
 [82 86 74]]
26.42996802640032


In [144]:
# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
mask = myarray[:,1] > 25
print (mask)
# Apply the mask
myarray[mask]

[ True  True  True  True False]


array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99]])

In [145]:
# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
mask = myarray <40
print (mask)
# apply the mask
myarray[mask]

[[False False  True]
 [False False  True]
 [False False False]
 [False False False]
 [ True  True  True]]


array([14, 20, 23,  2, 21])

### Solution 1.3: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]]


1. The first row:  [51 92 14]


2. The last column:  [14 20 74 99 21]


3. The 3rd column, 4th & 5th rows:  [99 21]


4. Multiply by 2: 
 [[102 184  28]
 [142 120  40]
 [164 172 148]
 [148 174 198]
 [ 46   4  42]]


5. Divide by 3: 
 [[17.         30.66666667  4.66666667]
 [23.66666667 20.          6.66666667]
 [27.33333333 28.66666667 24.66666667]
 [24.66666667 29.         33.        ]
 [ 7.66666667  0.66666667  7.        ]]


6. Add 12 to the first row: 
 [ 63 104  26]


7. The mean of the 1st column:  60.2


8. The median after removing the 2 smallest values:  74.0


9. The standard deviation is:  27.49051463799338


10. All values in 2nd column > 25: 
 [[29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]


11. All values < 40: 
 [ 1 29 37  1 20 32 21]


---
### Submit your assignment notebook! (Make sure you've changed the name to FIRSTNAME_LASTNAME_assign4): 

1.  Click the Share button in the upper-right hand corner of the notebook.
2.  Get the shareable link.
3.  Set condition to: "Anyone with the link can comment."

---