Objective 02 - set up a chi-square test for independence on two categorical variables

In [9]:
import numpy as np
from scipy.stats import chi2_contingency

# create a table using a NumPy Array
table = np.array([[200,290], [400,910]])

# print the table to check
print ('Table \n', table)

# seat the chi-square test
# stat, p, dof, \
stat, p, df, expected = chi2_contingency(table, correction=False)

# print stats
print ('Expected:  ',expected, '\n')
print (f'Chi square stat is :  {stat:.3f}', '\n')
print (f'p:  {p: .6f}', '\n')

Table 
 [[200 290]
 [400 910]]
Expected:   [[163.33333333 326.66666667]
 [436.66666667 873.33333333]] 

Chi square stat is :  16.965 

p:   0.000038 



In [1]:
import numpy as np


a1 = [13, 7, 10, 5, 13]
a2 = [5, 7, 4, 12, 9]
a3 = [5, 9, 14, 0, 10]
a4 = [12, 13, 8, 7, 7]
a5 = [7, 10, 9, 13, 6]
a6 = [8, 4, 5, 13, 5]

# combine them into a 6,5 array
dice = np.array([a1, a2, a3, a4, a5, a6])
print (dice)

[[13  7 10  5 13]
 [ 5  7  4 12  9]
 [ 5  9 14  0 10]
 [12 13  8  7  7]
 [ 7 10  9 13  6]
 [ 8  4  5 13  5]]


In [6]:
from scipy.stats import chi2_contingency

# perform the chi square test
stat, p, dof, expected = chi2_contingency(dice, correction= False)

print (stat, p, dof, expected)

40.37517168424223 0.0044771485808120706 20 [[9.6 9.6 9.6 9.6 9.6]
 [7.4 7.4 7.4 7.4 7.4]
 [7.6 7.6 7.6 7.6 7.6]
 [9.4 9.4 9.4 9.4 9.4]
 [9.  9.  9.  9.  9. ]
 [7.  7.  7.  7.  7. ]]
